In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
myarray = np.array(mylist)
myarray

array([1, 2, 3])

In [6]:
type(myarray)

numpy.ndarray

In [7]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [11]:
np.zeros(shape=(5,4,3)) #5array, 4rows, 3columns,,,  (0.) is a float value by default

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
arr = np.ones(shape=(6,9))
arr*10


array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.]])